name: Trigger Backend Data Reader

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files in the projects folder
        id: changed-files-specific
        uses: tj-actions/changed-files@v34
        with:
          files: |
            projects/**
          separator: ","

      - name: Print all changed files in the projects folder
        shell: bash
        run: |
          echo  ${{ steps.changed-files-specific.outputs.all_changed_files }}

      - name: Trigger a backend webhook that will read the changed files and update the projects accordingly
        uses: indiesdev/curl@v1.1
        if: steps.changed-files-specific.outputs.any_changed == 'true'
        env:
          API_ENDPOINT_SECRET_PATH: ${{ secrets.api_endpoint_secret_path }}
        with:
          url: https://api.santiment.net/projects_data_validator_webhook/"$API_ENDPOINT_SECRET_PATH/"
          method: "POST"
          accept: 200
          body: '{ "changed_files": "${{ steps.changed-files-specific.outputs.all_changed_files }}" }'
          timeout: 60000
          log-response: true
          retries: 3
